services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "testpassword"]

  tests:
    image: python:3.9-slim
    depends_on:
      - redis
    working_dir: /app
    volumes:
      - .:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: testpassword
    command: sh -c "pip install -r requirements.txt && pytest tests"
